vendors:
  - name: piaotian
    hostname: https://www.ptwxz.com
    novels:
    - name: 大奉打更人
      indexURL: /bookinfo/11/11014.html
    - name: 萬族之劫
      indexURL: /bookinfo/10/10811.html
    - name: 劍卒過河
      indexURL: /bookinfo/11/11374.html
    - name: 詭秘之主
      indexURL: /bookinfo/9/9459.html
    - name: 黎明之劍
      indexURL: /bookinfo/9/9483.html